[package]
name = "bascoin-wrpc-client"
description = "Bascoin wRPC client"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
include = [
    "src/**/*.rs",
    "benches/**/*.rs",
    "build.rs",
    "Cargo.toml",
    "Cargo.lock",
    "Resolvers.toml",
]

[features]
wasm32-sdk = ["bascoin-consensus-wasm/wasm32-sdk","bascoin-rpc-core/wasm32-sdk","workflow-rpc/wasm32-sdk"]
default = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-std.workspace = true
async-trait.workspace = true
borsh.workspace = true
cfg-if.workspace = true
futures.workspace = true
js-sys.workspace = true
bascoin-addresses.workspace = true
bascoin-consensus-core.workspace = true
bascoin-consensus-wasm.workspace = true
bascoin-notify.workspace = true
bascoin-rpc-core.workspace = true
bascoin-rpc-macros.workspace = true
paste.workspace = true
rand.workspace = true
regex.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
workflow-core.workspace = true
workflow-dom.workspace = true
workflow-http.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true
workflow-serializer.workspace = true
workflow-wasm.workspace = true
rustls.workspace = true
[lints]
workspace = true
